import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Loading from './loading';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import { Toaster } from 'react-hot-toast';
import { Suspense } from 'react';
import TanStackProvider from './components/TanStackProvider/TanStackProvider';
import Header from './components/Header/Header';
import ScrollToTop from './components/ScrollToTop/ScrollToTop';
import Footer from './components/Footer/Footer';

const interSans = Inter({
  variable: '--font-inter',
  subsets: ['latin', 'cyrillic'],
  display: 'swap',
  preload: true,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-scroll-behavior="smooth" data-theme="light" suppressHydrationWarning>
      <body className={`${interSans.variable} antialiased`}>
        <TanStackProvider>
          <div className="layout">
            <Suspense fallback={<Loading />}>
              <Header />
              <main>{children}</main>
              <Footer />
            </Suspense>
            <ScrollToTop />
          </div>
          <Toaster />
          <ReactQueryDevtools initialIsOpen={false} />
        </TanStackProvider>
      </body>
    </html>
  );
}
